### ISSUE TITLE
what is the shape of numpy in the pkl file 

### ISSUE THREAD

**Issue by Lvhhhh** [avalonstrel/GatedConvolution_pytorch#15]
The mask file should be a pkl file containing a numpy.array.
how to change the image mask to the pkl??
the shape of numpy in the pkl file is [1,1,h*w] or [h,w,1]???
the number of image in one pkl file is solo or multi? 
 
how to set the params to not use the MASKDATASET

**Comment by Iris6713** [comment]
I had the same problem， I want to konw how you solved it
