### ISSUE TITLE
gan and other losses are nan

### ISSUE THREAD

**Issue by tangeroo** [avalonstrel/GatedConvolution_pytorch#27]
@avalonstrel Hi,
  Thanks for your excellent work!
  When I train this net with my own data, I tried many times,also made learning rate smaller,Nan of losses happened soon or later.By the way,My mask configuration is irrmask/random_free_form.Do you have any suggestions for this promblem?
  Thanks.

**Comment by WangQinghuCS** [comment]
Hi, I come across the same problem. Can you tell me how to solve it?

**Comment by tangeroo** [comment]
@WangQinghuCS 
hi, in my case , it's because my dataset has some problem. My net input is calculated by (img-min)/(max-min)-1, however some images their max = min, so the input is nan. Maybe you can check your dataset.
