### ISSUE TITLE
about the package version

### ISSUE THREAD

**Issue by wdrink** [avalonstrel/GatedConvolution_pytorch#34]
Hi, thanks for your work in implementing the code with pytorch. I encountered an error that the netD will crash if using 64*64 as size of input img and mask:

RuntimeError: Calculated padded input size per channel: (3 x 3). Kernel size: (4 x 4). Kernel size can't be greater
than actual input size

The same code works well when I set the size to 128*128 or 256*256.

**Comment by Francoforever** [comment]
请问你解决了嘛？遇到同样问题 求教 多谢~~
------------
I solved. To modify these 2 lines to 256*256.
https://github.com/avalonstrel/GatedConvolution_pytorch/blob/22455dae24c42b58ac3fe4803c35487fe56d56dd/test_images.py#L33-L34
FYI~
